server:
  port: '8080'

spring:
  application:
    name: ita-compass-soccer-league
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/compass-soccer-league
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

logging:
  file:
    name: log-file.log

